apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mjda5s3j5-dotnet-basic
  janus-idp.io/tekton: mjda5s3j5-dotnet-basic
  backstage.io/kubernetes-id: mjda5s3j5-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mjda5s3j5-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
